/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ChartMaintainer struct for ChartMaintainer
type ChartMaintainer struct {
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
}
