/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListImageRegistryResponse struct for V1ListImageRegistryResponse
type V1ListImageRegistryResponse struct {
	Registries []V1ImageRegistry `json:"registries"`
}
