/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ChartMetadata struct for ChartMetadata
type ChartMetadata struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	ApiVersion string `json:"apiVersion,omitempty"`
	AppVersion string `json:"appVersion,omitempty"`
	Condition string `json:"condition,omitempty"`
	Dependencies []ChartDependency `json:"dependencies,omitempty"`
	Deprecated bool `json:"deprecated,omitempty"`
	Description string `json:"description,omitempty"`
	Home string `json:"home,omitempty"`
	Icon string `json:"icon,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	KubeVersion string `json:"kubeVersion,omitempty"`
	Maintainers []ChartMaintainer `json:"maintainers,omitempty"`
	Name string `json:"name,omitempty"`
	Sources []string `json:"sources,omitempty"`
	Tags string `json:"tags,omitempty"`
	Type string `json:"type,omitempty"`
	Version string `json:"version,omitempty"`
}
