/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ImageRegistry struct for V1ImageRegistry
type V1ImageRegistry struct {
	Domain string `json:"domain"`
	Name string `json:"name"`
	SecretName string `json:"secretName"`
}
