/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListProjectResponse struct for V1ListProjectResponse
type V1ListProjectResponse struct {
	Projects []V1ProjectBase `json:"projects"`
	Total int64 `json:"total"`
}
