/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ModelCodeInfo struct for ModelCodeInfo
type ModelCodeInfo struct {
	Branch string `json:"branch,omitempty"`
	Commit string `json:"commit,omitempty"`
	User string `json:"user,omitempty"`
}
