/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonChildResourceKind struct for CommonChildResourceKind
type CommonChildResourceKind struct {
	ApiVersion string `json:"apiVersion"`
	Kind string `json:"kind"`
	Selector map[string]string `json:"selector,omitempty"`
}
