/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ApplicationRollbackResponse struct for V1ApplicationRollbackResponse
type V1ApplicationRollbackResponse struct {
	Record V1WorkflowRecordBase `json:"record"`
}
