/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreatePolicyRequest struct for V1CreatePolicyRequest
type V1CreatePolicyRequest struct {
	Alias string `json:"alias"`
	Description string `json:"description"`
	EnvName string `json:"envName"`
	Name string `json:"name"`
	Properties string `json:"properties"`
	Type string `json:"type"`
	WorkflowPolicyBind []V1WorkflowPolicyBinding `json:"workflowPolicyBind"`
}
