/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1UserBase struct for V1UserBase
type V1UserBase struct {
	Alias string `json:"alias,omitempty"`
	CreateTime time.Time `json:"createTime"`
	Disabled bool `json:"disabled"`
	Email string `json:"email"`
	LastLoginTime time.Time `json:"lastLoginTime"`
	Name string `json:"name"`
}
