/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListApplicationResponse struct for V1ListApplicationResponse
type V1ListApplicationResponse struct {
	Applications []V1ApplicationBase `json:"applications"`
}
