/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1PipelineRunBriefing struct for V1PipelineRunBriefing
type V1PipelineRunBriefing struct {
	ContextName string `json:"contextName"`
	ContextValues []ModelValue `json:"contextValues"`
	EndTime string `json:"endTime"`
	Finished bool `json:"finished"`
	Message string `json:"message"`
	Phase string `json:"phase"`
	PipelineRunName string `json:"pipelineRunName"`
	StartTime string `json:"startTime"`
}
