/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1StepBase struct for V1StepBase
type V1StepBase struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Phase string `json:"phase"`
	Type string `json:"type"`
}
