/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AppCompareResponse struct for V1AppCompareResponse
type V1AppCompareResponse struct {
	BaseAppYAML string `json:"baseAppYAML"`
	DiffReport string `json:"diffReport"`
	IsDiff bool `json:"isDiff"`
	TargetAppYAML string `json:"targetAppYAML"`
}
