/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1Manifest struct for V1Manifest
type V1Manifest struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	Config V1Descriptor `json:"config"`
	Layers []V1Descriptor `json:"layers"`
	MediaType string `json:"mediaType,omitempty"`
	SchemaVersion int64 `json:"schemaVersion"`
}
