/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1RunStatInfo struct for V1RunStatInfo
type V1RunStatInfo struct {
	Fail int32 `json:"fail"`
	Success int32 `json:"success"`
	Total int32 `json:"total"`
}
