/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ApplicationDeployRequest struct for V1ApplicationDeployRequest
type V1ApplicationDeployRequest struct {
	CodeInfo ModelCodeInfo `json:"codeInfo,omitempty"`
	Force bool `json:"force"`
	ImageInfo ModelImageInfo `json:"imageInfo,omitempty"`
	Note string `json:"note"`
	TriggerType string `json:"triggerType"`
	WorkflowName string `json:"workflowName"`
}
