/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateApplicationTraitRequest struct for V1CreateApplicationTraitRequest
type V1CreateApplicationTraitRequest struct {
	Alias string `json:"alias,omitempty"`
	Description string `json:"description,omitempty"`
	Properties string `json:"properties"`
	Type string `json:"type"`
}
