/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AddonBaseStatus struct for V1AddonBaseStatus
type V1AddonBaseStatus struct {
	Name string `json:"name"`
	Phase string `json:"phase"`
}
