/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1alpha1WorkflowStepBase struct for V1alpha1WorkflowStepBase
type V1alpha1WorkflowStepBase struct {
	DependsOn []string `json:"dependsOn,omitempty"`
	If string `json:"if,omitempty"`
	Inputs []V1alpha1InputItem `json:"inputs,omitempty"`
	Meta V1alpha1WorkflowStepMeta `json:"meta,omitempty"`
	Name string `json:"name,omitempty"`
	Outputs []V1alpha1OutputItem `json:"outputs,omitempty"`
	Properties string `json:"properties,omitempty"`
	Timeout string `json:"timeout,omitempty"`
	Type string `json:"type"`
}
