/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1ApplicationTrait struct for V1ApplicationTrait
type V1ApplicationTrait struct {
	Alias string `json:"alias,omitempty"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description,omitempty"`
	Properties map[string]interface{} `json:"properties"`
	Type string `json:"type"`
	UpdateTime time.Time `json:"updateTime"`
}
