/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1alpha1WorkflowRunStatus struct for V1alpha1WorkflowRunStatus
type V1alpha1WorkflowRunStatus struct {
	Conditions []ConditionCondition `json:"conditions,omitempty"`
	ContextBackend V1ObjectReference `json:"contextBackend,omitempty"`
	EndTime string `json:"endTime,omitempty"`
	Finished bool `json:"finished"`
	Message string `json:"message,omitempty"`
	Mode V1alpha1WorkflowExecuteMode `json:"mode"`
	StartTime string `json:"startTime,omitempty"`
	Status string `json:"status"`
	Steps []V1alpha1WorkflowStepStatus `json:"steps,omitempty"`
	Suspend bool `json:"suspend"`
	SuspendState string `json:"suspendState,omitempty"`
	Terminated bool `json:"terminated"`
}
