/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateTargetRequest struct for V1UpdateTargetRequest
type V1UpdateTargetRequest struct {
	Alias string `json:"alias,omitempty"`
	Description string `json:"description,omitempty"`
	Variable map[string]interface{} `json:"variable,omitempty"`
}
