/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1EnableAddonRequest struct for V1EnableAddonRequest
type V1EnableAddonRequest struct {
	Args map[string]interface{} `json:"args,omitempty"`
	Clusters []string `json:"clusters,omitempty"`
	RegistryName string `json:"registryName,omitempty"`
	Version string `json:"version,omitempty"`
}
