/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1alpha1WorkflowStepMeta struct for V1alpha1WorkflowStepMeta
type V1alpha1WorkflowStepMeta struct {
	Alias string `json:"alias,omitempty"`
}
