/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1RunStat struct for V1RunStat
type V1RunStat struct {
	ActiveNum int32 `json:"activeNum"`
	Total V1RunStatInfo `json:"total"`
	Week []V1RunStatInfo `json:"week"`
}
