/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreatePermissionRequest struct for V1CreatePermissionRequest
type V1CreatePermissionRequest struct {
	Actions []string `json:"actions"`
	Alias string `json:"alias"`
	Effect string `json:"effect"`
	Name string `json:"name"`
	Resources []string `json:"resources"`
}
