/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonApplicationComponent struct for CommonApplicationComponent
type CommonApplicationComponent struct {
	DependsOn []string `json:"dependsOn,omitempty"`
	ExternalRevision string `json:"externalRevision,omitempty"`
	Inputs []V1alpha1InputItem `json:"inputs,omitempty"`
	Name string `json:"name"`
	Outputs []V1alpha1OutputItem `json:"outputs,omitempty"`
	Properties string `json:"properties,omitempty"`
	Scopes map[string]string `json:"scopes,omitempty"`
	Traits []CommonApplicationTrait `json:"traits,omitempty"`
	Type string `json:"type"`
}
