/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonAppStatus struct for CommonAppStatus
type CommonAppStatus struct {
	AppliedResources []CommonClusterObjectReference `json:"appliedResources,omitempty"`
	Components []V1ObjectReference `json:"components,omitempty"`
	Conditions []ConditionCondition `json:"conditions,omitempty"`
	LatestRevision CommonRevision `json:"latestRevision,omitempty"`
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	Policy []CommonPolicyStatus `json:"policy,omitempty"`
	Services []CommonApplicationComponentStatus `json:"services,omitempty"`
	Status string `json:"status,omitempty"`
	Workflow CommonWorkflowStatus `json:"workflow,omitempty"`
}
