/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListRevisionsResponse struct for V1ListRevisionsResponse
type V1ListRevisionsResponse struct {
	Revisions []V1ApplicationRevisionBase `json:"revisions"`
	Total int64 `json:"total"`
}
