/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonStatus struct for CommonStatus
type CommonStatus struct {
	CustomStatus string `json:"customStatus,omitempty"`
	HealthPolicy string `json:"healthPolicy,omitempty"`
}
