/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ModelProjectRef struct for ModelProjectRef
type ModelProjectRef struct {
	Name string `json:"name"`
	Roles []string `json:"roles"`
}
