/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListPipelineResponse struct for V1ListPipelineResponse
type V1ListPipelineResponse struct {
	Pipelines []V1PipelineListItem `json:"pipelines"`
	Total int32 `json:"total"`
}
