/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CloudproviderCloudCluster struct for CloudproviderCloudCluster
type CloudproviderCloudCluster struct {
	ApiServerURL string `json:"apiServerURL"`
	DashboardURL string `json:"dashboardURL"`
	Id string `json:"id"`
	Labels map[string]string `json:"labels"`
	Name string `json:"name"`
	Provider string `json:"provider"`
	RegionID string `json:"regionID"`
	Status string `json:"status"`
	Type string `json:"type"`
	VpcID string `json:"vpcID"`
	Zone string `json:"zone"`
	ZoneID string `json:"zoneID"`
}
