/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateApplicationRequest struct for V1CreateApplicationRequest
type V1CreateApplicationRequest struct {
	Alias string `json:"alias,omitempty"`
	Component V1CreateComponentRequest `json:"component"`
	Description string `json:"description,omitempty"`
	EnvBinding []V1EnvBinding `json:"envBinding,omitempty"`
	Icon string `json:"icon"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
	Project string `json:"project"`
}
