/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListEnvResponse struct for V1ListEnvResponse
type V1ListEnvResponse struct {
	Envs []V1Env `json:"envs"`
	Total int64 `json:"total"`
}
