/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1ComponentBase struct for V1ComponentBase
type V1ComponentBase struct {
	Alias string `json:"alias"`
	ComponentType string `json:"componentType"`
	CreateTime time.Time `json:"createTime"`
	Creator string `json:"creator,omitempty"`
	DependsOn []string `json:"dependsOn"`
	Description string `json:"description"`
	Icon string `json:"icon,omitempty"`
	Inputs []V1alpha1InputItem `json:"inputs,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Main bool `json:"main"`
	Name string `json:"name"`
	Outputs []V1alpha1OutputItem `json:"outputs,omitempty"`
	Traits []V1ApplicationTrait `json:"traits"`
	UpdateTime time.Time `json:"updateTime"`
	WorkloadType CommonWorkloadTypeDescriptor `json:"workloadType,omitempty"`
}
