/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1NameAlias struct for V1NameAlias
type V1NameAlias struct {
	Alias string `json:"alias"`
	Name string `json:"name"`
}
