/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListWorkflowResponse struct for V1ListWorkflowResponse
type V1ListWorkflowResponse struct {
	Workflows []V1WorkflowBase `json:"workflows"`
}
