/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1Env struct for V1Env
type V1Env struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Project V1NameAlias `json:"project"`
	Targets []V1NameAlias `json:"targets,omitempty"`
	UpdateTime time.Time `json:"updateTime"`
}
