/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateConfigRequest struct for V1CreateConfigRequest
type V1CreateConfigRequest struct {
	Alias string `json:"alias"`
	Description string `json:"description"`
	Name string `json:"name"`
	Properties string `json:"properties,omitempty"`
	Template V1NamespacedName `json:"template"`
}
