/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1PermissionBase struct for V1PermissionBase
type V1PermissionBase struct {
	Actions []string `json:"actions"`
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Effect string `json:"effect"`
	Name string `json:"name"`
	Resources []string `json:"resources"`
	UpdateTime time.Time `json:"updateTime"`
}
