/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// TypesSecretReference struct for TypesSecretReference
type TypesSecretReference struct {
	Name string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}
