/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateContextValuesRequest struct for V1UpdateContextValuesRequest
type V1UpdateContextValuesRequest struct {
	Values []ModelValue `json:"values"`
}
