/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ConditionCondition struct for ConditionCondition
type ConditionCondition struct {
	LastTransitionTime string `json:"lastTransitionTime"`
	Message string `json:"message,omitempty"`
	Reason string `json:"reason"`
	Status string `json:"status"`
	Type string `json:"type"`
}
