/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonDefinitionReference struct for CommonDefinitionReference
type CommonDefinitionReference struct {
	Name string `json:"name"`
	Version string `json:"version,omitempty"`
}
