/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// ConfigDistribution struct for ConfigDistribution
type ConfigDistribution struct {
	Application TypesNamespacedName `json:"application"`
	Configs []ConfigNamespacedName `json:"configs"`
	CreatedTime time.Time `json:"createdTime"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Status CommonAppStatus `json:"status"`
	Targets []ConfigClusterTarget `json:"targets"`
}
