/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AppDryRunResponse struct for V1AppDryRunResponse
type V1AppDryRunResponse struct {
	Message string `json:"message,omitempty"`
	Success bool `json:"success"`
	Yaml string `json:"yaml"`
}
