/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonPolicyStatus struct for CommonPolicyStatus
type CommonPolicyStatus struct {
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
	Type string `json:"type"`
}
