/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateCloudClusterResponse struct for V1CreateCloudClusterResponse
type V1CreateCloudClusterResponse struct {
	ClusterID string `json:"clusterID"`
	ClusterName string `json:"clusterName"`
	Status string `json:"status"`
}
