/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1GetPipelineRunOutputResponse struct for V1GetPipelineRunOutputResponse
type V1GetPipelineRunOutputResponse struct {
	Outputs []V1StepOutputBase `json:"outputs"`
}
