/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonKubeParameter struct for CommonKubeParameter
type CommonKubeParameter struct {
	Description string `json:"description,omitempty"`
	FieldPaths []string `json:"fieldPaths"`
	Name string `json:"name"`
	Required bool `json:"required,omitempty"`
	Type string `json:"type"`
}
