/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1SecretReference SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace
type V1SecretReference struct {
	// name is unique within a namespace to reference a secret resource.
	Name string `json:"name,omitempty"`
	// namespace defines the space within which the secret name must be unique.
	Namespace string `json:"namespace,omitempty"`
}
