/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListConfigResponse struct for V1ListConfigResponse
type V1ListConfigResponse struct {
	Configs []V1Config `json:"configs"`
}
