/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ConfigClusterTargetStatus struct for ConfigClusterTargetStatus
type ConfigClusterTargetStatus struct {
	Application ConfigNamespacedName `json:"application"`
	ClusterName string `json:"clusterName"`
	Message string `json:"message"`
	Namespace string `json:"namespace"`
	Status string `json:"status"`
}
