/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListClusterResponse struct for V1ListClusterResponse
type V1ListClusterResponse struct {
	Clusters []V1ClusterBase `json:"clusters"`
	Total int64 `json:"total"`
}
