/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1GetPipelineRunLogResponse struct for V1GetPipelineRunLogResponse
type V1GetPipelineRunLogResponse struct {
	Id string `json:"id"`
	Log string `json:"log"`
	Name string `json:"name"`
	Phase string `json:"phase"`
	Source string `json:"source"`
	Type string `json:"type"`
}
