/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// UtilsCondition struct for UtilsCondition
type UtilsCondition struct {
	Action string `json:"action,omitempty"`
	JsonKey string `json:"jsonKey"`
	Op string `json:"op,omitempty"`
	Value string `json:"value"`
}
