/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListTerraformProviderResponse struct for V1ListTerraformProviderResponse
type V1ListTerraformProviderResponse struct {
	Providers []V1TerraformProvider `json:"providers"`
}
