/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi

// V1AddonStatusResponse struct for V1AddonStatusResponse
type V1AddonStatusResponse struct {
	AllClusters      []V1NameAlias          `json:"allClusters,omitempty"`
	AppStatus        CommonAppStatus        `json:"appStatus,omitempty"`
	Args             map[string]interface{} `json:"args"`
	Clusters         map[string]interface{} `json:"clusters,omitempty"`
	EnablingProgress V1EnablingProgress     `json:"enabling_progress,omitempty"`
	InstalledVersion string                 `json:"installedVersion,omitempty"`
	Name             string                 `json:"name"`
	Phase            string                 `json:"phase"`
}
