/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListCloudClusterResponse struct for V1ListCloudClusterResponse
type V1ListCloudClusterResponse struct {
	Clusters []CloudproviderCloudCluster `json:"clusters"`
	Total int32 `json:"total"`
}
