/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListConfigDistributionResponse struct for V1ListConfigDistributionResponse
type V1ListConfigDistributionResponse struct {
	Distributions []ConfigDistribution `json:"distributions"`
}
