/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1LoginRequest struct for V1LoginRequest
type V1LoginRequest struct {
	Code string `json:"code,omitempty"`
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
}
