/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1PipelineRun struct for V1PipelineRun
type V1PipelineRun struct {
	ContextName string `json:"contextName"`
	ContextValues []ModelValue `json:"contextValues"`
	PipelineName string `json:"pipelineName"`
	PipelineRunName string `json:"pipelineRunName"`
	Project V1NameAlias `json:"project"`
	Record int64 `json:"record"`
	Spec V1alpha1WorkflowRunSpec `json:"spec"`
	Status V1alpha1WorkflowRunStatus `json:"status"`
}
