/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// AddonMeta struct for AddonMeta
type AddonMeta struct {
	Dependencies []AddonDependency `json:"dependencies,omitempty"`
	DeployTo AddonDeployTo `json:"deployTo,omitempty"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	Invisible bool `json:"invisible"`
	Name string `json:"name"`
	NeedNamespace []string `json:"needNamespace,omitempty"`
	System AddonSystemRequirements `json:"system,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Url string `json:"url,omitempty"`
	Version string `json:"version"`
}
