/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1SimpleResponse struct for V1SimpleResponse
type V1SimpleResponse struct {
	Status string `json:"status"`
}
