/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// AddonOssAddonSource struct for AddonOssAddonSource
type AddonOssAddonSource struct {
	Bucket string `json:"bucket"`
	EndPoint string `json:"end_point"`
	Path string `json:"path"`
}
