/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ConfigClusterTarget struct for ConfigClusterTarget
type ConfigClusterTarget struct {
	ClusterName string `json:"clusterName"`
	Namespace string `json:"namespace"`
}
