/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1ApplicationTriggerBase struct for V1ApplicationTriggerBase
type V1ApplicationTriggerBase struct {
	Alias string `json:"alias,omitempty"`
	ComponentName string `json:"componentName,omitempty"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	PayloadType string `json:"payloadType"`
	Registry string `json:"registry"`
	Token string `json:"token"`
	Type string `json:"type"`
	UpdateTime time.Time `json:"updateTime"`
	WorkflowName string `json:"workflowName"`
}
