/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi

// V1HandleApplicationTriggerWebhookRequest struct for V1HandleApplicationTriggerWebhookRequest
type V1HandleApplicationTriggerWebhookRequest struct {
	CodeInfo ModelCodeInfo          `json:"codeInfo,omitempty"`
	Upgrade  map[string]interface{} `json:"upgrade,omitempty"`
}
