/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AppDryRunReq struct for V1AppDryRunReq
type V1AppDryRunReq struct {
	DryRunType string `json:"dryRunType"`
	Env string `json:"env"`
	Version string `json:"version"`
	Workflow string `json:"workflow"`
}
