/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListApplicationPolicy struct for V1ListApplicationPolicy
type V1ListApplicationPolicy struct {
	Policies []V1PolicyBase `json:"policies"`
}
