/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// ModelWorkflowStepStatus struct for ModelWorkflowStepStatus
type ModelWorkflowStepStatus struct {
	Alias string `json:"alias"`
	FirstExecuteTime time.Time `json:"firstExecuteTime,omitempty"`
	Id string `json:"id"`
	LastExecuteTime time.Time `json:"lastExecuteTime,omitempty"`
	Message string `json:"message,omitempty"`
	Name string `json:"name"`
	Phase string `json:"phase,omitempty"`
	Reason string `json:"reason,omitempty"`
	SubSteps []ModelStepStatus `json:"subSteps,omitempty"`
	Type string `json:"type,omitempty"`
}
