/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1alpha1OutputItem struct for V1alpha1OutputItem
type V1alpha1OutputItem struct {
	Name string `json:"name"`
	ValueFrom string `json:"valueFrom"`
}
