/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1alpha1WorkflowExecuteMode struct for V1alpha1WorkflowExecuteMode
type V1alpha1WorkflowExecuteMode struct {
	Steps string `json:"steps,omitempty"`
	SubSteps string `json:"subSteps,omitempty"`
}
