/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateDefinitionStatusRequest struct for V1UpdateDefinitionStatusRequest
type V1UpdateDefinitionStatusRequest struct {
	HiddenInUI bool `json:"hiddenInUI"`
	Type string `json:"type"`
}
