/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1Hash struct for V1Hash
type V1Hash struct {
	Algorithm string `json:"Algorithm"`
	Hex string `json:"Hex"`
}
