/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1StepOutputBase struct for V1StepOutputBase
type V1StepOutputBase struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Phase string `json:"phase"`
	Type string `json:"type"`
	Values []V1OutputVar `json:"values"`
}
