/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateApplicationTriggerRequest struct for V1CreateApplicationTriggerRequest
type V1CreateApplicationTriggerRequest struct {
	Alias string `json:"alias,omitempty"`
	ComponentName string `json:"componentName,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	PayloadType string `json:"payloadType"`
	Registry string `json:"registry,omitempty"`
	Type string `json:"type"`
	WorkflowName string `json:"workflowName"`
}
