/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListUserResponse struct for V1ListUserResponse
type V1ListUserResponse struct {
	Total int64 `json:"total"`
	Users []V1DetailUserResponse `json:"users"`
}
