/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ModelValue struct for ModelValue
type ModelValue struct {
	Key string `json:"key"`
	Value string `json:"value"`
}
