/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1DetailAddonResponse struct for V1DetailAddonResponse
type V1DetailAddonResponse struct {
	AvailableVersions []string `json:"availableVersions"`
	Definitions []V1AddonDefinition `json:"definitions"`
	Dependencies []AddonDependency `json:"dependencies,omitempty"`
	DeployTo AddonDeployTo `json:"deployTo,omitempty"`
	Description string `json:"description"`
	Detail string `json:"detail,omitempty"`
	Icon string `json:"icon"`
	Invisible bool `json:"invisible"`
	Name string `json:"name"`
	NeedNamespace []string `json:"needNamespace,omitempty"`
	RegistryName string `json:"registryName,omitempty"`
	Schema string `json:"schema"`
	System AddonSystemRequirements `json:"system,omitempty"`
	Tags []string `json:"tags,omitempty"`
	UiSchema []UtilsUiParameter `json:"uiSchema"`
	Url string `json:"url,omitempty"`
	Version string `json:"version"`
}
