/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreatePipelineRequest struct for V1CreatePipelineRequest
type V1CreatePipelineRequest struct {
	Alias string `json:"alias,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	Spec ModelWorkflowSpec `json:"spec"`
}
