/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1PolicyBase struct for V1PolicyBase
type V1PolicyBase struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Creator string `json:"creator"`
	Description string `json:"description"`
	EnvName string `json:"envName"`
	Name string `json:"name"`
	Properties map[string]interface{} `json:"properties"`
	Type string `json:"type"`
	UpdateTime time.Time `json:"updateTime"`
}
