/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonWorkloadTypeDescriptor struct for CommonWorkloadTypeDescriptor
type CommonWorkloadTypeDescriptor struct {
	Definition CommonWorkloadGvk `json:"definition,omitempty"`
	Type string `json:"type,omitempty"`
}
