/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1SystemVersion struct for V1SystemVersion
type V1SystemVersion struct {
	GitVersion string `json:"gitVersion"`
	VelaVersion string `json:"velaVersion"`
}
