/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ModelImageInfo struct for ModelImageInfo
type ModelImageInfo struct {
	Repository ModelImageRepository `json:"repository,omitempty"`
	Resource ModelImageResource `json:"resource,omitempty"`
	Type string `json:"type"`
}
