/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// AddonHelmSource struct for AddonHelmSource
type AddonHelmSource struct {
	InsecureSkipTLS bool `json:"insecureSkipTLS,omitempty"`
	Password string `json:"password,omitempty"`
	Url string `json:"url,omitempty"`
	Username string `json:"username,omitempty"`
}
