/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ConditionConditionedStatus struct for ConditionConditionedStatus
type ConditionConditionedStatus struct {
	Conditions []ConditionCondition `json:"conditions,omitempty"`
}
