/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateUserRequest struct for V1CreateUserRequest
type V1CreateUserRequest struct {
	Alias string `json:"alias,omitempty"`
	Email string `json:"email"`
	Name string `json:"name"`
	Password string `json:"password"`
	Roles []string `json:"roles"`
}
