/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// UtilsOption struct for UtilsOption
type UtilsOption struct {
	Label string `json:"label"`
	Value string `json:"value"`
}
