/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1PipelineMeta struct for V1PipelineMeta
type V1PipelineMeta struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description"`
	Name string `json:"name"`
	Project V1NameAlias `json:"project"`
}
