/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonTerraform struct for CommonTerraform
type CommonTerraform struct {
	Configuration string `json:"configuration"`
	CustomRegion string `json:"customRegion,omitempty"`
	DeleteResource bool `json:"deleteResource,omitempty"`
	GitCredentialsSecretReference V1SecretReference `json:"gitCredentialsSecretReference,omitempty"`
	Path string `json:"path,omitempty"`
	ProviderRef TypesReference `json:"providerRef,omitempty"`
	Type string `json:"type,omitempty"`
	WriteConnectionSecretToRef TypesSecretReference `json:"writeConnectionSecretToRef,omitempty"`
}
