/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateProjectUserRequest struct for V1UpdateProjectUserRequest
type V1UpdateProjectUserRequest struct {
	UserRoles []string `json:"userRoles"`
}
