/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListRolesResponse struct for V1ListRolesResponse
type V1ListRolesResponse struct {
	Roles []V1RoleBase `json:"roles"`
	Total int64 `json:"total"`
}
