/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AppResetResponse struct for V1AppResetResponse
type V1AppResetResponse struct {
	IsReset bool `json:"isReset"`
}
