/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi

// AddonDeployTo struct for AddonDeployTo
type AddonDeployTo struct {
	DisableControlPlane bool `json:"disableControlPlane"`
	// RuntimeCluster bool `json:"runtimeCluster"`
	RuntimeCluster bool `json:"runtime_cluster,omitempty"`
}
