/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1GetLoginTypeResponse struct for V1GetLoginTypeResponse
type V1GetLoginTypeResponse struct {
	LoginType string `json:"loginType"`
}
