/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1ConfigTemplateDetail struct for V1ConfigTemplateDetail
type V1ConfigTemplateDetail struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Schema string `json:"schema"`
	Scope string `json:"scope"`
	Sensitive bool `json:"sensitive"`
	UiSchema []UtilsUiParameter `json:"uiSchema"`
}
