/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonApplicationTraitStatus struct for CommonApplicationTraitStatus
type CommonApplicationTraitStatus struct {
	Healthy bool `json:"healthy"`
	Message string `json:"message,omitempty"`
	Type string `json:"type"`
}
