/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1SystemInfoRequest struct for V1SystemInfoRequest
type V1SystemInfoRequest struct {
	DexUserDefaultProjects []ModelProjectRef `json:"dexUserDefaultProjects,omitempty"`
	EnableCollection bool `json:"enableCollection"`
	LoginType string `json:"loginType"`
	VelaAddress string `json:"velaAddress,omitempty"`
}
