/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1DetailComponentResponse struct for V1DetailComponentResponse
type V1DetailComponentResponse struct {
	Alias string `json:"alias"`
	AppPrimaryKey string `json:"appPrimaryKey"`
	CreateTime time.Time `json:"createTime"`
	Creator string `json:"creator"`
	Definition V1beta1ComponentDefinitionSpec `json:"definition"`
	DependsOn []string `json:"dependsOn,omitempty"`
	Description string `json:"description,omitempty"`
	ExternalRevision string `json:"externalRevision,omitempty"`
	Icon string `json:"icon,omitempty"`
	Inputs []V1alpha1InputItem `json:"inputs,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Main bool `json:"main"`
	Name string `json:"name"`
	Outputs []V1alpha1OutputItem `json:"outputs,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Scopes map[string]string `json:"scopes,omitempty"`
	Traits []ModelApplicationTrait `json:"traits,omitempty"`
	Type string `json:"type"`
	UpdateTime time.Time `json:"updateTime"`
	WorkloadType CommonWorkloadTypeDescriptor `json:"workloadType,omitempty"`
}
