/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1EnablingProgress struct for V1EnablingProgress
type V1EnablingProgress struct {
	EnabledComponents int32 `json:"enabled_components"`
	TotalComponents int32 `json:"total_components"`
}
