/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1StatisticInfo struct for V1StatisticInfo
type V1StatisticInfo struct {
	AppCount string `json:"appCount,omitempty"`
	ClusterCount string `json:"clusterCount,omitempty"`
	ComponentDefinitionTopList []string `json:"componentDefinitionTopList,omitempty"`
	EnableAddonList map[string]string `json:"enableAddonList,omitempty"`
	PolicyDefinitionTopList []string `json:"policyDefinitionTopList,omitempty"`
	TraitDefinitionTopList []string `json:"traitDefinitionTopList,omitempty"`
	UpdateTime time.Time `json:"updateTime,omitempty"`
	WorkflowDefinitionTopList []string `json:"workflowDefinitionTopList,omitempty"`
}
