/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ApplicationResponse struct for V1ApplicationResponse
type V1ApplicationResponse struct {
	ApiVersion string `json:"apiVersion"`
	Kind string `json:"kind"`
	Spec V1beta1ApplicationSpec `json:"spec"`
	Status CommonAppStatus `json:"status"`
}
