/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListConfigTemplateResponse struct for V1ListConfigTemplateResponse
type V1ListConfigTemplateResponse struct {
	Templates []V1ConfigTemplate `json:"templates"`
}
