/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonApplicationTrait struct for CommonApplicationTrait
type CommonApplicationTrait struct {
	Properties string `json:"properties,omitempty"`
	Type string `json:"type"`
}
