/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ImageInfo struct for V1ImageInfo
type V1ImageInfo struct {
	Info V1ConfigFile `json:"info,omitempty"`
	Manifest V1Manifest `json:"manifest"`
	Message string `json:"message,omitempty"`
	Name string `json:"name"`
	Registry string `json:"registry"`
	SecretNames []string `json:"secretNames"`
	Size int64 `json:"size"`
}
