/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateApplicationTemplateRequest struct for V1CreateApplicationTemplateRequest
type V1CreateApplicationTemplateRequest struct {
	Description string `json:"description"`
	TemplateName string `json:"templateName"`
	Version string `json:"version"`
}
