/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateApplicationTraitRequest struct for V1UpdateApplicationTraitRequest
type V1UpdateApplicationTraitRequest struct {
	Alias string `json:"alias,omitempty"`
	Description string `json:"description,omitempty"`
	Properties string `json:"properties"`
}
