/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1History struct for V1History
type V1History struct {
	Author string `json:"author,omitempty"`
	Comment string `json:"comment,omitempty"`
	Created string `json:"created,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	EmptyLayer bool `json:"empty_layer,omitempty"`
}
