/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1beta1AppPolicy struct for V1beta1AppPolicy
type V1beta1AppPolicy struct {
	Name string `json:"name"`
	Properties string `json:"properties,omitempty"`
	Type string `json:"type"`
}
