/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// AddonGitlabAddonSource struct for AddonGitlabAddonSource
type AddonGitlabAddonSource struct {
	Path string `json:"path,omitempty"`
	Repo string `json:"repo,omitempty"`
	Token string `json:"token,omitempty"`
	Url string `json:"url,omitempty"`
}
