/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonKube struct for CommonKube
type CommonKube struct {
	Parameters []CommonKubeParameter `json:"parameters,omitempty"`
	Template string `json:"template"`
}
