/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AppCompareReq struct for V1AppCompareReq
type V1AppCompareReq struct {
	CompareLatestWithRunning V1CompareLatestWithRunningOption `json:"compareLatestWithRunning,omitempty"`
	CompareRevisionWithLatest V1CompareRevisionWithLatestOption `json:"compareRevisionWithLatest,omitempty"`
	CompareRevisionWithRunning V1CompareRevisionWithRunningOption `json:"compareRevisionWithRunning,omitempty"`
}
