/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonRevision struct for CommonRevision
type CommonRevision struct {
	Name string `json:"name"`
	Revision int64 `json:"revision"`
	RevisionHash string `json:"revisionHash,omitempty"`
}
