/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1InputVar struct for V1InputVar
type V1InputVar struct {
	From string `json:"from"`
	FromStep string `json:"fromStep"`
	ParameterKey string `json:"parameterKey"`
	Value string `json:"value"`
}
