/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AddProjectUserRequest struct for V1AddProjectUserRequest
type V1AddProjectUserRequest struct {
	UserName string `json:"userName"`
	UserRoles []string `json:"userRoles"`
}
