/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi

// UtilsUiParameter struct for UtilsUiParameter
type UtilsUiParameter struct {
	Additional              bool                `json:"additional,omitempty"`
	AdditionalParameter     *UtilsUiParameter   `json:"additionalParameter,omitempty"`
	Conditions              []UtilsCondition    `json:"conditions,omitempty"`
	Description             string              `json:"description"`
	Disable                 bool                `json:"disable,omitempty"`
	JsonKey                 string              `json:"jsonKey"`
	Label                   string              `json:"label"`
	Sort                    int32               `json:"sort"`
	Style                   UtilsStyle          `json:"style,omitempty"`
	SubParameterGroupOption []UtilsGroupOption  `json:"subParameterGroupOption,omitempty"`
	SubParameters           []*UtilsUiParameter `json:"subParameters,omitempty"`
	UiType                  string              `json:"uiType"`
	Validate                UtilsValidate       `json:"validate,omitempty"`
}
