/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1EnvBindingBase struct for V1EnvBindingBase
type V1EnvBindingBase struct {
	Alias string `json:"alias,omitempty"`
	AppDeployName string `json:"appDeployName"`
	AppDeployNamespace string `json:"appDeployNamespace"`
	ComponentSelector V1ComponentSelector `json:"componentSelector,omitempty"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	TargetNames []string `json:"targetNames"`
	Targets []V1EnvBindingTarget `json:"targets,omitempty"`
	UpdateTime time.Time `json:"updateTime"`
	Workflow V1NameAlias `json:"workflow"`
}
