/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateClusterRequest struct for V1CreateClusterRequest
type V1CreateClusterRequest struct {
	Alias string `json:"alias,omitempty"`
	DashboardURL string `json:"dashboardURL,omitempty"`
	Description string `json:"description,omitempty"`
	Icon string `json:"icon"`
	KubeConfig string `json:"kubeConfig,omitempty"`
	KubeConfigSecret string `json:"kubeConfigSecret,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
}
