/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateUserRequest struct for V1UpdateUserRequest
type V1UpdateUserRequest struct {
	Alias string `json:"alias,omitempty"`
	Email string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
	Roles []string `json:"roles"`
}
