/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// ChartDependency struct for ChartDependency
type ChartDependency struct {
	Alias string `json:"alias,omitempty"`
	Condition string `json:"condition,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	ImportValues []string `json:"import-values,omitempty"`
	Name string `json:"name"`
	Repository string `json:"repository"`
	Tags []string `json:"tags,omitempty"`
	Version string `json:"version,omitempty"`
}
