/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// AddonSystemRequirements struct for AddonSystemRequirements
type AddonSystemRequirements struct {
	Kubernetes string `json:"kubernetes,omitempty"`
	Vela string `json:"vela,omitempty"`
}
