/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1ApplicationBase struct for V1ApplicationBase
type V1ApplicationBase struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
	Project V1ProjectBase `json:"project"`
	ReadOnly bool `json:"readOnly,omitempty"`
	UpdateTime time.Time `json:"updateTime"`
}
