/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// RepoChartVersion struct for RepoChartVersion
type RepoChartVersion struct {
	Metadata ChartMetadata `json:"Metadata"`
	Checksum string `json:"checksum,omitempty"`
	Created time.Time `json:"created,omitempty"`
	Digest string `json:"digest,omitempty"`
	Engine string `json:"engine,omitempty"`
	Removed bool `json:"removed,omitempty"`
	TillerVersion string `json:"tillerVersion,omitempty"`
	Url string `json:"url,omitempty"`
	Urls []string `json:"urls"`
}
