/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1AddonInfo struct for V1AddonInfo
type V1AddonInfo struct {
	Meta AddonMeta `json:"Meta"`
	RegistryName string `json:"registryName"`
}
