/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonSchematic struct for CommonSchematic
type CommonSchematic struct {
	Cue CommonCue `json:"cue,omitempty"`
	Helm CommonHelm `json:"helm,omitempty"`
	Kube CommonKube `json:"kube,omitempty"`
	Terraform CommonTerraform `json:"terraform,omitempty"`
}
