/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CloudShellPrepareResponse struct for V1CloudShellPrepareResponse
type V1CloudShellPrepareResponse struct {
	Message string `json:"message"`
	Status string `json:"status"`
}
