/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1HealthConfig struct for V1HealthConfig
type V1HealthConfig struct {
	Interval int32 `json:"Interval,omitempty"`
	Retries int32 `json:"Retries,omitempty"`
	StartPeriod int32 `json:"StartPeriod,omitempty"`
	Test []string `json:"Test,omitempty"`
	Timeout int32 `json:"Timeout,omitempty"`
}
