/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CreateContextValuesRequest struct for V1CreateContextValuesRequest
type V1CreateContextValuesRequest struct {
	Name string `json:"name"`
	Values []ModelValue `json:"values"`
}
