/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ListApplicationEnvBinding struct for V1ListApplicationEnvBinding
type V1ListApplicationEnvBinding struct {
	EnvBindings []V1EnvBindingBase `json:"envBindings"`
}
