/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateApplicationComponentRequest struct for V1UpdateApplicationComponentRequest
type V1UpdateApplicationComponentRequest struct {
	Alias string `json:"alias,omitempty"`
	DependsOn []string `json:"dependsOn,omitempty"`
	Description string `json:"description,omitempty"`
	Icon string `json:"icon,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Properties string `json:"properties,omitempty"`
}
