/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonApplicationComponentStatus struct for CommonApplicationComponentStatus
type CommonApplicationComponentStatus struct {
	Cluster string `json:"cluster,omitempty"`
	Env string `json:"env,omitempty"`
	Healthy bool `json:"healthy"`
	Message string `json:"message,omitempty"`
	Name string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
	Scopes []V1ObjectReference `json:"scopes,omitempty"`
	Traits []CommonApplicationTraitStatus `json:"traits,omitempty"`
	WorkloadDefinition CommonWorkloadGvk `json:"workloadDefinition,omitempty"`
}
