/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ComponentListResponse struct for V1ComponentListResponse
type V1ComponentListResponse struct {
	Components []V1ComponentBase `json:"components"`
}
