/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// TypesNamespacedName struct for TypesNamespacedName
type TypesNamespacedName struct {
	Name string `json:"Name"`
	Namespace string `json:"Namespace"`
}
