/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1CompareRevisionWithRunningOption struct for V1CompareRevisionWithRunningOption
type V1CompareRevisionWithRunningOption struct {
	Revision string `json:"revision,omitempty"`
}
