/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1WorkflowPolicyBinding struct for V1WorkflowPolicyBinding
type V1WorkflowPolicyBinding struct {
	Name string `json:"name"`
	Steps []string `json:"steps"`
}
