/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1RootFs struct for V1RootFs
type V1RootFs struct {
	DiffIds []V1Hash `json:"diff_ids"`
	Type string `json:"type"`
}
