/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// UtilsValidate struct for UtilsValidate
type UtilsValidate struct {
	DefaultValue string `json:"defaultValue,omitempty"`
	Immutable bool `json:"immutable"`
	Max float64 `json:"max,omitempty"`
	MaxLength int32 `json:"maxLength,omitempty"`
	Min float64 `json:"min,omitempty"`
	MinLength int32 `json:"minLength,omitempty"`
	Options []UtilsOption `json:"options,omitempty"`
	Pattern string `json:"pattern,omitempty"`
	Required bool `json:"required,omitempty"`
}
