/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1DetailApplicationResponse struct for V1DetailApplicationResponse
type V1DetailApplicationResponse struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description"`
	EnvBindings []string `json:"envBindings"`
	Icon string `json:"icon"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
	Policies []string `json:"policies"`
	Project V1ProjectBase `json:"project"`
	ReadOnly bool `json:"readOnly,omitempty"`
	ResourceInfo V1ApplicationResourceInfo `json:"resourceInfo"`
	UpdateTime time.Time `json:"updateTime"`
}
