/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi

// V1ListContextValueResponse struct for V1ListContextValueResponse
type V1ListContextValueResponse struct {
	Contexts map[string]any `json:"contexts"`
	Total    int32          `json:"total"`
}
