/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1GetPipelineRunInputResponse struct for V1GetPipelineRunInputResponse
type V1GetPipelineRunInputResponse struct {
	Inputs []V1StepInputBase `json:"inputs"`
}
