/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// CommonHelm struct for CommonHelm
type CommonHelm struct {
	Release string `json:"release"`
	Repository string `json:"repository"`
}
