/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
import (
	"time"
)
// V1DetailWorkflowResponse struct for V1DetailWorkflowResponse
type V1DetailWorkflowResponse struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Default bool `json:"default"`
	Description string `json:"description"`
	Enable bool `json:"enable"`
	EnvName string `json:"envName"`
	Mode string `json:"mode"`
	Name string `json:"name"`
	Steps []V1WorkflowStep `json:"steps,omitempty"`
	SubMode string `json:"subMode"`
	UpdateTime time.Time `json:"updateTime"`
}
