/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1ChartVersionListResponse struct for V1ChartVersionListResponse
type V1ChartVersionListResponse struct {
	Versions []RepoChartVersion `json:"versions"`
}
