/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1UpdateUiSchemaRequest struct for V1UpdateUiSchemaRequest
type V1UpdateUiSchemaRequest struct {
	Type string `json:"type"`
	UiSchema []UtilsUiParameter `json:"uiSchema"`
}
