/*
 * vela-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vealapi
// V1EnvBindingTarget struct for V1EnvBindingTarget
type V1EnvBindingTarget struct {
	Alias string `json:"alias"`
	Cluster V1ClusterTarget `json:"cluster,omitempty"`
	Name string `json:"name"`
}
